
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/header/Header";
import Footer from "./components/footer/Footer";
import FirstLoading from "./components/firstLoading/FirstLoading";
import SideLabel from "./components/sideLabel/SideLabel";
import SideLabel2 from "./components/sideLabel2/SideLabel2";
import I18nProvider from "./I18nProvider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Ashley",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <I18nProvider>
          <FirstLoading>
            <SideLabel />
            <SideLabel2 />
            <Header />
            {children}
            <Footer />
          </FirstLoading>
        </I18nProvider>
      </body>
    </html>
  );
}
